apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-survey-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-survey-app
  template:
    metadata:
      labels:
        app: my-survey-app
    spec:
      containers:
      - name: my-survey-app
        image: 232183/my-survey-app:latest  # Use your numeric username here
        ports:
        - containerPort: 80
